
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 13 08:36:56 BRT 2017
//----------------------------------------------------

package jflex;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FLOAT_SIGN = 9;
  public static final int REPETITION = 12;
  public static final int ENDING_LINE = 3;
  public static final int INT = 7;
  public static final int OP_ARITMETICO = 14;
  public static final int OP_RELACIONAL = 15;
  public static final int NUM_REAL = 16;
  public static final int ERROR = 10;
  public static final int EXPOENT = 4;
  public static final int FUNCTION = 23;
  public static final int ID = 2;
  public static final int PARAMETERS = 20;
  public static final int START_PROGRAM = 22;
  public static final int COMMA = 19;
  public static final int EOF = 0;
  public static final int END_PROGRAM = 21;
  public static final int COMMENT = 24;
  public static final int LEFT_BRACKET = 18;
  public static final int error = 1;
  public static final int SELECTION = 11;
  public static final int ASSIGNMENT = 6;
  public static final int OP_LOGICO = 13;
  public static final int STRINGS = 5;
  public static final int RIGHT_BRACKET = 17;
  public static final int DOUBLE = 8;
}

